server:
  port: 8081
spring:
  application:
    name: hmdp
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${lbytech.db.host}:3306/hm-dianping?useSSL=false&serverTimezone=UTC
    username: root
    password: ${lbytech.db.password}
    hikari:
      max-lifetime: 180000
  redis:
    host: ${lbytech.redis.host}
    port: 6379
    password: ${lbytech.redis.password}
    lettuce:
      pool:
        enabled: true # 开启线程池自动开启心跳机制，避免连接被断开
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug